#spring.datasource.url: jdbc:h2:mem:testdb
#spring.datasource.driverClassName: org.h2.Driver
#spring.datasource.username: sa
#spring.datasource.password:

#spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto: create-drop
#spring.jpa.show-sql: false
#spring.jpa.properties.hibernate.format_sql: false

# ================= MySQL ?????? ================
spring:
  datasource:
    # 1. URL: ??? ?????, ??, ?????? ??? ??
    url: jdbc:mysql://gradcheck-dev-mysql.chysugycag07.ap-northeast-2.rds.amazonaws.com:3306/teamdb_dev?serverTimezone=UTC&characterEncoding=UTF-8
    # 2. ??? ??
    username: backend
    # 3. ????
    password: Backend123!
    # MySQL ???? ??? ??
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # JPA/Hibernate ??
    hibernate:
      # ?? ddl-auto? ?? ??? ?????.
      # update: (??) ?? ??(Entity)? ????? DB ???? ??????. (??? ??)
      # validate: ?? ??? DB ??? ??? ????? ??? ???.
      # none: ???? ?? ????. (?? ???? ??)
      ddl-auto: update
    properties:
      hibernate:
        # MySQL? SQL ??? ????? ??
        dialect: org.hibernate.dialect.MySQLDialect
        # SQL ??? ?? ?? ?? (? ?? ? ????)
        format_sql: true
    # ???? SQL ??? ??? ?? ?? ? (?? ? ??)
    #show-sql: true
    #properties.hibernate.format_sql: true
    # JPA? ???? SQL ??? ??? ??
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    com.team.grade_checklist: INFO
    org.springframework.security: INFO
    # ??????? ???? ?? SQL?? ????? ??? ??
    org.hibernate.SQL: debug
    # SQL ?? ????? ???? ?? ??
    org.hibernate.type.descriptor.sql: trace